//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobOpeningsMVCClient.JobSearchService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobDTO", Namespace="http://schemas.datacontract.org/2004/07/WCFJobSearchService")]
    [System.SerializableAttribute()]
    public partial class JobDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfVacanciesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimarySkillField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyLocation {
            get {
                return this.CompanyLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyLocationField, value) != true)) {
                    this.CompanyLocationField = value;
                    this.RaisePropertyChanged("CompanyLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfVacancies {
            get {
                return this.NumberOfVacanciesField;
            }
            set {
                if ((this.NumberOfVacanciesField.Equals(value) != true)) {
                    this.NumberOfVacanciesField = value;
                    this.RaisePropertyChanged("NumberOfVacancies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimarySkill {
            get {
                return this.PrimarySkillField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimarySkillField, value) != true)) {
                    this.PrimarySkillField = value;
                    this.RaisePropertyChanged("PrimarySkill");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleDTO", Namespace="http://schemas.datacontract.org/2004/07/WCFJobSearchService")]
    [System.SerializableAttribute()]
    public partial class RoleDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleID {
            get {
                return this.RoleIDField;
            }
            set {
                if ((this.RoleIDField.Equals(value) != true)) {
                    this.RoleIDField = value;
                    this.RaisePropertyChanged("RoleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JobSearchService.IJobSearchService")]
    public interface IJobSearchService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobSearchService/GetAllJobs", ReplyAction="http://tempuri.org/IJobSearchService/GetAllJobsResponse")]
        JobOpeningsMVCClient.JobSearchService.JobDTO[] GetAllJobs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobSearchService/GetAllJobs", ReplyAction="http://tempuri.org/IJobSearchService/GetAllJobsResponse")]
        System.Threading.Tasks.Task<JobOpeningsMVCClient.JobSearchService.JobDTO[]> GetAllJobsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobSearchService/GetJobsByRole", ReplyAction="http://tempuri.org/IJobSearchService/GetJobsByRoleResponse")]
        JobOpeningsMVCClient.JobSearchService.JobDTO[] GetJobsByRole(int roleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobSearchService/GetJobsByRole", ReplyAction="http://tempuri.org/IJobSearchService/GetJobsByRoleResponse")]
        System.Threading.Tasks.Task<JobOpeningsMVCClient.JobSearchService.JobDTO[]> GetJobsByRoleAsync(int roleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobSearchService/GetAllJobRoles", ReplyAction="http://tempuri.org/IJobSearchService/GetAllJobRolesResponse")]
        JobOpeningsMVCClient.JobSearchService.RoleDTO[] GetAllJobRoles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJobSearchService/GetAllJobRoles", ReplyAction="http://tempuri.org/IJobSearchService/GetAllJobRolesResponse")]
        System.Threading.Tasks.Task<JobOpeningsMVCClient.JobSearchService.RoleDTO[]> GetAllJobRolesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJobSearchServiceChannel : JobOpeningsMVCClient.JobSearchService.IJobSearchService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JobSearchServiceClient : System.ServiceModel.ClientBase<JobOpeningsMVCClient.JobSearchService.IJobSearchService>, JobOpeningsMVCClient.JobSearchService.IJobSearchService {
        
        public JobSearchServiceClient() {
        }
        
        public JobSearchServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JobSearchServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobSearchServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobSearchServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public JobOpeningsMVCClient.JobSearchService.JobDTO[] GetAllJobs() {
            return base.Channel.GetAllJobs();
        }
        
        public System.Threading.Tasks.Task<JobOpeningsMVCClient.JobSearchService.JobDTO[]> GetAllJobsAsync() {
            return base.Channel.GetAllJobsAsync();
        }
        
        public JobOpeningsMVCClient.JobSearchService.JobDTO[] GetJobsByRole(int roleId) {
            return base.Channel.GetJobsByRole(roleId);
        }
        
        public System.Threading.Tasks.Task<JobOpeningsMVCClient.JobSearchService.JobDTO[]> GetJobsByRoleAsync(int roleId) {
            return base.Channel.GetJobsByRoleAsync(roleId);
        }
        
        public JobOpeningsMVCClient.JobSearchService.RoleDTO[] GetAllJobRoles() {
            return base.Channel.GetAllJobRoles();
        }
        
        public System.Threading.Tasks.Task<JobOpeningsMVCClient.JobSearchService.RoleDTO[]> GetAllJobRolesAsync() {
            return base.Channel.GetAllJobRolesAsync();
        }
    }
}
