//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFJobSearchService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int ID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyLocation { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string PrimarySkill { get; set; }
        public int NumberOfVacancies { get; set; }
    }
}
